{{- if .Values.ingress.enabled -}}
{{- $paths := .Values.ingress.paths -}}
{{- $extraPaths := .Values.ingress.extraPaths -}}
{{- $pathType := .Values.ingress.pathType -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "helm-chart.name" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "helm-chart.labels" | nindent 4 }}
    {{- with .Values.ingress.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.ingress.annotations }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  {{- with .Values.ingress.ingressClassName }}
  ingressClassName: {{ . }}
  {{- end }}
  rules:
  {{- if .Values.ingress.hosts }}
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host | quote }}
      http:
        paths:
          {{- with $extraPaths }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- range $p := $paths }}
          - path: {{ $p }}
            pathType: {{ $pathType }}
            backend:
              service:
                name: {{ include "helm-chart.name" $ }}
                port:
                  {{- if kindIs "float64" .Values.service.port }}
                  number: {{ .Values.service.port }}
                  {{- else }}
                  name: {{ .Values.service.port }}
                  {{- end }}
          {{- end -}}
    {{- end -}}
  {{- else }}
    - http:
        paths:
          {{- with $extraPaths }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- range $p := $paths }}
          - path: {{ $p }}
            pathType: {{ $pathType }}
            backend:
              service:
                name: {{ include "helm-chart.name" $ }}
                port:
                  {{- if kindIs "float64" .Values.service.port }}
                  number: {{ .Values.service.port }}
                  {{- else }}
                  name: {{ .Values.service.port }}
                  {{- end }}
          {{- end -}}
  {{- end -}}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end -}}
{{- end -}}
